mira:
#publish all joint states:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
#position controllers:
  roll_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: roll_joint
    pid: {p: 1.0, i: 0.1 , d: 0.0}
  pitch_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: roll_pitch_joint
    pid: {p: 1.0, i: 0.1 , d: 0.0}
  yaw_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: yaw_pitch_joint
    pid: {p: 1.0, i: 0.1 , d: 0.0}